#!/bin/bash

# 1. Cài Zsh nếu chưa có
if ! command -v zsh &> /dev/null; then
    echo "Zsh chưa được cài. Cài đặt..."
    sudo apt update && sudo apt install -y zsh
fi

# 2. Cài Oh My Zsh nếu chưa có
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    echo "Cài đặt Oh My Zsh..."
    export RUNZSH=no
    export CHSH=no
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting

# 6. Ghi đè dòng plugins trong ~/.zshrc
echo "Cập nhật plugins trong ~/.zshrc..."
sed -i 's/^plugins=(.*)$/plugins=(git z zsh-autosuggestions zsh-syntax-highlighting fzf python docker laravel emoji)/' ~/.zshrc || \
echo "plugins=(git z zsh-autosuggestions fzf python docker laravel emoji)" >> ~/.zshrc

echo "Xong! Đã chạy: source ~/.zshrc hoặc mở terminal mới để áp dụng."
cp -f ./custom.zsh $ZSH_CUSTOM/
source ~/.zshrc
